spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_example
    username: root
    password: root

  liquibase:
    change-log: classpath:/db/changelog/2022/10/migration.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: papikitornik
  expiration: 330000

logging:
 logback:
  rollingpolicy:
   file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
   max-file-size: 10MB
 file:
  name: D:\rest-example\log\application.log
 pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
 level:
  root: info
  am.solido: info
cb:
  url: https://cb.am/latest.json.php











